### PR TITLE
Drop "credentials" input and prep for 1.0 release

### LINKED ISSUE #166: Incorrect output URL when version is github.sha
### TL;DR

When version input is specified as `${{github.sha}}`, the action outputs an incorrect URL.

**Expected behavior**

Normally, when providing a version for a service, the URL produced looks like this:

```
VERSION-dot-SERVICE-dot-PROJECT_ID.REGION_ID.r.appspot.com
```

**Observed behavior**

However, when I specified `${{ github.sha }}` for the version, the output URL comes out with `.` instead of `-dot-`, which doesn't work:

```
VERSION.SERVICE.PROJECT_ID.REGION_ID.r.appspot.com
```

NB: The version gets deployed correctly and I can visit it by using the correct URL (with `-dot-`s).

### Reproduction

**Action YAML**

```yaml
uses: google-github-actions/deploy-appengine@main
with:
  project_id: ${{ env.PROJECT_ID }}
  credentials: ${{ env.SERVICE_ACCOUNT_KEY }}
  deliverables: ${{ env.CONFIG_FILE }}
  promote: false
  version: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) ||  github.sha  }}
```

### LINKED ISSUE #255: Make sure all inputs are documented in README
> It appears the `flags` input is not mentioned in README, probably it can be updated so with a sample from this issue.

_Originally posted by @hunghvu in https://github.com/google-github-actions/deploy-appengine/issues/252#issuecomment-1105720001_

### LINKED ISSUE #268: Output URL isn't compatabile with IAP
### TL;DR

The .outputs.url url seems to have the following structure: https://<version>.<project_name>.ew.r.appspot.com/
When adding IAP (identity aware proxy) and using flag `promote: false` this URL errored with error code 52.

### Detailed design

I am using this GitHub Action to deploy a branch to a staging environment meaning I use `promote: false`. This worked correctly however when I added IAP to my App Engine this started erroring.

Accessing the version directly through Google App Engine however gave me the following URL: https://<version>-dot-<project_name>.ew.r.appspot.com/ which did seem to work.

### Additional information

This is the step from my .yaml:
```
      - id: 'deploy'
        name: 'Deploy the current branch to google app engine with no traffic'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          promote: false
```
I referenced the url by using: `[this url](${{ steps.deploy.outputs.url }})`

### PR DESCRIPTION
**Pull request by sethvargo**
This drops the long-deprecated "credentials" input and pulls many of the expensive integration tests into unit tests which assert the same behavior. It also switches to using the JSON output from the "gcloud app deploy" command instead of parsing the text output, since that has proven to be unstable.

Closes #166
Closes #255
Closes #268
Closes #277 
Closes #278

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -174,8 +142,15 @@ export async function run(): Promise<void> {
...
 
     // Set url as output.
-    // TODO: update this to use JSON or YAML machine-readable output instead.
-    setUrlOutput(output.stdout + output.stderr);
+    const response = parseDeployResponse(output.stdout);
+    if (response) {
+      setOutput('name', response.name);
+      setOutput('serviceAccountEmail', response.serviceAccountEmail);
+      setOutput('versionURL', response.versionURL);
+      setOutput('url', response.versionURL);
```
Comment (verbanicm) [inline src/main.ts:150]: Will these ever be different, say when promote is false?

File: src/main.ts [hunk 2]
```diff
@@ -75,26 +60,19 @@ export async function run(): Promise<void> {
...
     // Get action inputs.
-    let projectId = getInput('project_id');
+    const projectId = getInput('project_id');
     const cwd = getInput('working_directory');
     const deliverables = getInput('deliverables');
     const imageUrl = getInput('image_url');
     const version = getInput('version');
-    const promote = getInput('promote');
-    const credentials = getInput('credentials');
+    const promote = (getInput('promote') || '').toLowerCase() == 'true';
```
Comment (verbanicm) [inline src/main.ts:68]: nit: prefer `===`

File: .github/workflows/label.yml [hunk 3]
```diff
@@ -1,19 +0,0 @@
-name: 'label'
```
Comment (verbanicm) [inline .github/workflows/label.yml:1]: Why was this removed, just curious?

File: .github/workflows/integration.yml [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+      with:
+        node-version: '16.x'
+
+    - name: 'npm build'
+      run: 'npm ci && npm run build'
+
+    - uses: 'google-github-actions/auth@main'
+      with:
+        workload_identity_provider: '${{ secrets.WIF_PROVIDER_NAME }}'
+        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT_EMAIL }}'
```
Comment (verbanicm) [inline .github/workflows/integration.yml:37]: This secret doesnt exist....

File: src/main.ts (hunk 1 above)
Comment (sethvargo) [reply src/main.ts:150]: Yea - they are not provided with `--no-promote`. I have a warning message.

File: .github/workflows/label.yml (hunk 3 above)
Comment (sethvargo) [reply .github/workflows/label.yml:1]: I don't think we use it (that label doesn't even exist on some repos). I think it's an artifact from when everything was in one repo.

File: src/main.ts (hunk 1 above)
Comment (verbanicm) [reply src/main.ts:150]: I meant `https://....appspot.com/v1/app` vs `https://....appspot.com/app` would we care about the difference? Seems like it might be useful, IE main url vs version url (im not even sure if this is given in output).

Comment (sethvargo) [reply src/main.ts:150]: Oh sorry. They are both the same. `url` is there for backwards compat, but it's always been the version url.

**Review by verbanicm — APPROVED** [review]
